[2025-07-25T08:39:32.682+0000] {processor.py:161} INFO - Started process (PID=159) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:39:32.694+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T08:39:32.757+0000] {logging_mixin.py:188} INFO - [2025-07-25T08:39:32.744+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:39:33.007+0000] {logging_mixin.py:188} INFO - [2025-07-25T08:39:32.969+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T08:39:33.048+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:39:34.445+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 1.812 seconds
[2025-07-25T08:40:05.354+0000] {processor.py:161} INFO - Started process (PID=164) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:40:05.364+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T08:40:05.394+0000] {logging_mixin.py:188} INFO - [2025-07-25T08:40:05.390+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:40:05.460+0000] {logging_mixin.py:188} INFO - [2025-07-25T08:40:05.440+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T08:40:05.471+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:40:05.767+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 0.509 seconds
[2025-07-25T08:40:38.189+0000] {processor.py:161} INFO - Started process (PID=169) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:40:38.208+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T08:40:38.238+0000] {logging_mixin.py:188} INFO - [2025-07-25T08:40:38.233+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:40:38.488+0000] {logging_mixin.py:188} INFO - [2025-07-25T08:40:38.432+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T08:40:38.548+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:40:39.264+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 1.271 seconds
[2025-07-25T08:41:10.586+0000] {processor.py:161} INFO - Started process (PID=174) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:41:10.603+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T08:41:10.618+0000] {logging_mixin.py:188} INFO - [2025-07-25T08:41:10.618+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:41:10.785+0000] {logging_mixin.py:188} INFO - [2025-07-25T08:41:10.748+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T08:41:10.788+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:41:11.037+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 0.556 seconds
[2025-07-25T08:41:42.216+0000] {processor.py:161} INFO - Started process (PID=179) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:41:42.229+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T08:41:42.244+0000] {logging_mixin.py:188} INFO - [2025-07-25T08:41:42.237+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:41:42.301+0000] {logging_mixin.py:188} INFO - [2025-07-25T08:41:42.294+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T08:41:42.303+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:41:42.393+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 0.217 seconds
[2025-07-25T08:42:12.927+0000] {processor.py:161} INFO - Started process (PID=184) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:42:12.930+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T08:42:12.941+0000] {logging_mixin.py:188} INFO - [2025-07-25T08:42:12.939+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:42:13.002+0000] {logging_mixin.py:188} INFO - [2025-07-25T08:42:12.988+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T08:42:13.008+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:42:13.074+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 0.172 seconds
[2025-07-25T08:42:45.199+0000] {processor.py:161} INFO - Started process (PID=189) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:42:45.232+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T08:42:45.366+0000] {logging_mixin.py:188} INFO - [2025-07-25T08:42:45.353+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:42:45.713+0000] {logging_mixin.py:188} INFO - [2025-07-25T08:42:45.622+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T08:42:45.744+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:42:47.474+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 3.046 seconds
[2025-07-25T08:43:18.241+0000] {processor.py:161} INFO - Started process (PID=194) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:43:18.244+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T08:43:18.256+0000] {logging_mixin.py:188} INFO - [2025-07-25T08:43:18.255+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:43:18.314+0000] {logging_mixin.py:188} INFO - [2025-07-25T08:43:18.301+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T08:43:18.317+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:43:18.417+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 0.207 seconds
[2025-07-25T08:43:49.220+0000] {processor.py:161} INFO - Started process (PID=199) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:43:49.259+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T08:43:49.299+0000] {logging_mixin.py:188} INFO - [2025-07-25T08:43:49.292+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:43:49.323+0000] {logging_mixin.py:188} INFO - [2025-07-25T08:43:49.317+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T08:43:49.328+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:43:49.482+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 0.307 seconds
[2025-07-25T08:44:20.578+0000] {processor.py:161} INFO - Started process (PID=204) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:44:20.585+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T08:44:20.614+0000] {logging_mixin.py:188} INFO - [2025-07-25T08:44:20.612+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:44:20.683+0000] {logging_mixin.py:188} INFO - [2025-07-25T08:44:20.676+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T08:44:20.687+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:44:20.840+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 0.463 seconds
[2025-07-25T08:44:51.865+0000] {processor.py:161} INFO - Started process (PID=209) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:44:51.876+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T08:44:51.908+0000] {logging_mixin.py:188} INFO - [2025-07-25T08:44:51.905+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:44:51.979+0000] {logging_mixin.py:188} INFO - [2025-07-25T08:44:51.960+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T08:44:51.993+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:44:53.003+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 1.383 seconds
[2025-07-25T08:45:24.157+0000] {processor.py:161} INFO - Started process (PID=214) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:45:24.165+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T08:45:24.174+0000] {logging_mixin.py:188} INFO - [2025-07-25T08:45:24.173+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:45:24.283+0000] {logging_mixin.py:188} INFO - [2025-07-25T08:45:24.268+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T08:45:24.286+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:45:24.357+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 0.217 seconds
[2025-07-25T08:45:54.665+0000] {processor.py:161} INFO - Started process (PID=219) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:45:54.667+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T08:45:54.670+0000] {logging_mixin.py:188} INFO - [2025-07-25T08:45:54.670+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:45:54.709+0000] {logging_mixin.py:188} INFO - [2025-07-25T08:45:54.694+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T08:45:54.712+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:45:54.793+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 0.148 seconds
[2025-07-25T08:46:25.515+0000] {processor.py:161} INFO - Started process (PID=224) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:46:25.517+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T08:46:25.521+0000] {logging_mixin.py:188} INFO - [2025-07-25T08:46:25.520+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:46:25.554+0000] {logging_mixin.py:188} INFO - [2025-07-25T08:46:25.546+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T08:46:25.558+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T08:46:25.608+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 0.106 seconds
[2025-07-25T09:50:16.096+0000] {processor.py:161} INFO - Started process (PID=159) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:50:16.125+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T09:50:16.159+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:50:16.159+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:50:16.267+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:50:16.257+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T09:50:16.278+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:50:16.387+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 0.334 seconds
[2025-07-25T09:50:46.811+0000] {processor.py:161} INFO - Started process (PID=165) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:50:46.817+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T09:50:46.830+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:50:46.825+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:50:46.988+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:50:46.931+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T09:50:47.011+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:50:47.270+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 0.482 seconds
[2025-07-25T09:51:17.684+0000] {processor.py:161} INFO - Started process (PID=170) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:51:17.694+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T09:51:17.702+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:51:17.701+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:51:17.801+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:51:17.776+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T09:51:17.814+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:51:17.977+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 0.326 seconds
[2025-07-25T09:51:48.802+0000] {processor.py:161} INFO - Started process (PID=175) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:51:48.805+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T09:51:48.812+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:51:48.810+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:51:48.858+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:51:48.848+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T09:51:48.862+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:51:48.904+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 0.118 seconds
[2025-07-25T09:52:19.293+0000] {processor.py:161} INFO - Started process (PID=180) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:52:19.295+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T09:52:19.298+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:52:19.298+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:52:19.334+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:52:19.328+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T09:52:19.337+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:52:19.376+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 0.095 seconds
[2025-07-25T09:52:49.644+0000] {processor.py:161} INFO - Started process (PID=185) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:52:49.650+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T09:52:49.655+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:52:49.654+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:52:49.687+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:52:49.681+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T09:52:49.691+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:52:49.742+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 0.110 seconds
[2025-07-25T09:52:50.812+0000] {processor.py:161} INFO - Started process (PID=190) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:52:50.814+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T09:52:50.818+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:52:50.818+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:52:50.876+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:52:50.867+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T09:52:50.879+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:52:50.912+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 0.109 seconds
[2025-07-25T09:53:21.190+0000] {processor.py:161} INFO - Started process (PID=195) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:53:21.193+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T09:53:21.199+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:53:21.198+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:53:21.234+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:53:21.226+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T09:53:21.238+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:53:21.280+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 0.100 seconds
[2025-07-25T09:53:51.700+0000] {processor.py:161} INFO - Started process (PID=200) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:53:51.704+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T09:53:51.711+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:53:51.710+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:53:51.787+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:53:51.771+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T09:53:51.792+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:53:51.829+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 0.157 seconds
[2025-07-25T09:54:22.091+0000] {processor.py:161} INFO - Started process (PID=205) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:54:22.092+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T09:54:22.096+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:54:22.095+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:54:22.132+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:54:22.124+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T09:54:22.135+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:54:22.170+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 0.090 seconds
[2025-07-25T09:54:52.437+0000] {processor.py:161} INFO - Started process (PID=210) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:54:52.440+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T09:54:52.446+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:54:52.445+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:54:52.488+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:54:52.475+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T09:54:52.494+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:54:52.546+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 0.126 seconds
[2025-07-25T09:55:23.245+0000] {processor.py:161} INFO - Started process (PID=215) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:55:23.249+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T09:55:23.258+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:55:23.257+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:55:23.336+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:55:23.318+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T09:55:23.352+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:55:23.473+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 0.250 seconds
[2025-07-25T09:55:53.752+0000] {processor.py:161} INFO - Started process (PID=220) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:55:53.755+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T09:55:53.759+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:55:53.759+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:55:53.799+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:55:53.791+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T09:55:53.802+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:55:53.842+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 0.103 seconds
[2025-07-25T09:56:24.336+0000] {processor.py:161} INFO - Started process (PID=225) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:56:24.340+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T09:56:24.349+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:56:24.347+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:56:24.424+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:56:24.407+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T09:56:24.430+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:56:24.513+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 0.224 seconds
[2025-07-25T09:56:54.662+0000] {processor.py:161} INFO - Started process (PID=230) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:56:54.665+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T09:56:54.668+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:56:54.668+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:56:54.703+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:56:54.696+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T09:56:54.706+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:56:54.765+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 0.116 seconds
[2025-07-25T09:57:24.981+0000] {processor.py:161} INFO - Started process (PID=235) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:57:24.983+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T09:57:24.987+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:57:24.986+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:57:25.023+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:57:25.014+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T09:57:25.026+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:57:25.065+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 0.095 seconds
[2025-07-25T09:57:55.509+0000] {processor.py:161} INFO - Started process (PID=240) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:57:55.512+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T09:57:55.516+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:57:55.515+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:57:55.568+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:57:55.559+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T09:57:55.572+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:57:55.656+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 0.160 seconds
[2025-07-25T09:58:25.906+0000] {processor.py:161} INFO - Started process (PID=245) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:58:25.908+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T09:58:25.912+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:58:25.911+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:58:25.950+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:58:25.941+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T09:58:25.954+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:58:25.995+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 0.100 seconds
[2025-07-25T09:58:56.308+0000] {processor.py:161} INFO - Started process (PID=250) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:58:56.310+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T09:58:56.314+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:58:56.314+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:58:56.347+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:58:56.339+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T09:58:56.351+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:58:56.392+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 0.100 seconds
[2025-07-25T09:59:26.874+0000] {processor.py:161} INFO - Started process (PID=255) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:59:26.878+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T09:59:26.888+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:59:26.887+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:59:26.921+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:59:26.913+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T09:59:26.925+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:59:27.025+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 0.170 seconds
[2025-07-25T09:59:57.321+0000] {processor.py:161} INFO - Started process (PID=260) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:59:57.323+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T09:59:57.326+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:59:57.325+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:59:57.355+0000] {logging_mixin.py:188} INFO - [2025-07-25T09:59:57.349+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T09:59:57.357+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T09:59:57.410+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 0.102 seconds
[2025-07-25T10:00:27.846+0000] {processor.py:161} INFO - Started process (PID=265) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T10:00:27.848+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T10:00:27.852+0000] {logging_mixin.py:188} INFO - [2025-07-25T10:00:27.851+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T10:00:27.885+0000] {logging_mixin.py:188} INFO - [2025-07-25T10:00:27.878+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T10:00:27.888+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T10:00:27.929+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 0.094 seconds
[2025-07-25T10:00:58.425+0000] {processor.py:161} INFO - Started process (PID=270) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T10:00:58.427+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T10:00:58.433+0000] {logging_mixin.py:188} INFO - [2025-07-25T10:00:58.432+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T10:00:58.466+0000] {logging_mixin.py:188} INFO - [2025-07-25T10:00:58.460+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T10:00:58.474+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T10:00:58.540+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 0.130 seconds
[2025-07-25T10:01:28.915+0000] {processor.py:161} INFO - Started process (PID=275) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T10:01:28.924+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T10:01:28.928+0000] {logging_mixin.py:188} INFO - [2025-07-25T10:01:28.927+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T10:01:28.967+0000] {logging_mixin.py:188} INFO - [2025-07-25T10:01:28.953+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T10:01:28.974+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T10:01:29.053+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 0.154 seconds
[2025-07-25T10:01:59.594+0000] {processor.py:161} INFO - Started process (PID=280) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T10:01:59.595+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T10:01:59.599+0000] {logging_mixin.py:188} INFO - [2025-07-25T10:01:59.598+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T10:01:59.629+0000] {logging_mixin.py:188} INFO - [2025-07-25T10:01:59.621+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T10:01:59.632+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T10:01:59.666+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 0.082 seconds
[2025-07-25T10:02:30.037+0000] {processor.py:161} INFO - Started process (PID=285) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T10:02:30.038+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T10:02:30.042+0000] {logging_mixin.py:188} INFO - [2025-07-25T10:02:30.041+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T10:02:30.072+0000] {logging_mixin.py:188} INFO - [2025-07-25T10:02:30.066+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T10:02:30.074+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T10:02:30.112+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 0.087 seconds
[2025-07-25T10:03:00.657+0000] {processor.py:161} INFO - Started process (PID=290) to work on /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T10:03:00.659+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/yfinance_etl_dag.py for tasks to queue
[2025-07-25T10:03:00.662+0000] {logging_mixin.py:188} INFO - [2025-07-25T10:03:00.662+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T10:03:00.696+0000] {logging_mixin.py:188} INFO - [2025-07-25T10:03:00.689+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/yfinance_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/yfinance_etl_dag.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-07-25T10:03:00.700+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/yfinance_etl_dag.py
[2025-07-25T10:03:00.737+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/yfinance_etl_dag.py took 0.089 seconds
